services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    environment:
      - PASSWORD=${PASSWORD}
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.flame.entrypoints=https
      - traefik.http.routers.flame.rule=Host(`example.com`)
      - traefik.http.services.flame.loadbalancer.server.port=5005
      - traefik.http.routers.flame.tls=true
networks:
  traefik:
    external: true