services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - WEBTHEME=${WEBTHEME}
      - PIHOLE_DOMAIN=${PIHOLE_DOMAIN}
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.entrypoints=https
      - traefik.http.routers.pihole.rule=Host(`example.com`)
      - traefik.http.middlewares.pihole.addprefix.prefix=/admin
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.routers.pihole.tls=true
networks:
  traefik:
    external: true
