services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr/config:/config
      - /path/to/media/movies:/movies
    ports:
      - 7878:7878
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=https
      - traefik.http.routers.radarr.rule=Host(`example.com`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.tls=true
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_movies
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
      - TORRENTING_PORT=${TORRENTING_PORT}
    volumes:
      - ./qbittorrent/config:/config
      - /path/to/media/movies/complete:/downloads
    ports:
      - 8087:8087
      - 6881:6881
      - 6881:6881/udp
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbitmovies.entrypoints=https
      - traefik.http.routers.qbitmovies.rule=Host(`example.com`)
      - traefik.http.services.qbitmovies.loadbalancer.server.port=8087
      - traefik.http.routers.qbitmovies.tls=true
networks:
  traefik:
    external: true
