services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3999:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.routers.homepage.rule=Host(`example.com`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - "traefik.http.routers.homepage.middlewares=homepage-auth"
      - "traefik.http.middlewares.homepage-auth.basicauth.users=" # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
      - traefik.http.routers.homepage.tls=true
networks:
  traefik:
    external: true