---
title: # Page title

background:
  image: # link for background image
  blur: sm
  saturate: 100
  brightness: 80
  opacity: 50

theme: dark
color: slate

headerStyle: boxedWidgets

target: _self

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google

showStats: true
statusStyle: "dot"

layout:
  - Media server:
  - Torrent:
  - Services:
  - Administration:
  - Developer:
  - Production:
  - Development:

providers:
  openmeteo: #openmeteo api link