services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '9002:80'
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - local
networks:
  local:
    external: true
