services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    restart: always
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ${DOCKGE_STACKS_DIR}:${DOCKGE_STACKS_DIR}
    environment:
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.entrypoints=https
      - traefik.http.routers.dockge.rule=Host(`example.com`)
      - traefik.http.services.dockge.loadbalancer.server.port=5001
      - traefik.http.routers.dockge.tls=true
networks:
  traefik:
    external: true
